# Generated by Django 6.0.2 on 2026-03-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
