# Generated by Django 6.0.2 on 2026-03-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cotnent',
            new_name='content',
        ),
    ]
